export const LOAD_TASKS_REQUESTING = 'LOAD_TASKS_REQUESTING';
export const LOAD_TASKS_REQUESTING_SUCCESS = 'LOAD_TASKS_REQUESTING_SUCCESS';
export const LOAD_TASKS_REQUESTING_FAILED = 'LOAD_TASKS_REQUESTING_FAILED';

export const DELETE_TASKS_REQUESTING = 'DELETE_TASKS_REQUESTING';
export const DELETE_TASKS_REQUESTING_SUCCESS = 'DELETE_TASKS_REQUESTING_SUCCESS';
export const DELETE_TASKS_REQUESTING_FAILED = 'DELETE_TASKS_REQUESTING_FAILED';

export const EDIT_TASKS_REQUESTING = 'EDIT_TASKS_REQUESTING';
export const EDIT_TASKS_REQUESTING_SUCCESS = 'EDIT_TASKS_REQUESTING_SUCCESS';
export const EDIT_TASKS_REQUESTING_FAILED = 'EDIT_TASKS_REQUESTING_FAILED';

export const ADD_TASKS_REQUESTING = 'ADD_TASKS_REQUESTING';
export const ADD_TASKS_REQUESTING_SUCCESS = 'ADD_TASKS_REQUESTING_SUCCESS';
export const ADD_TASKS_REQUESTING_FAILED = 'ADD_TASKS_REQUESTING_FAILED';